[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/..."
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "0.14.13"

[dev-dependencies]
test = "2.0.0"
bench = "1.0.0"

[toolchain]
moc = "0.14.13"
pocket-ic = "4.0.0"
