[package]
name = ""
version = ""
description = ""
repository = "https://github.com/research-ag/..."
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "0.9.1"

[dev-dependencies]
test = "1.0.1"

